news/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('create/', views.create_article, name='create_article'),
    path('', views.article_list, name='home'),
    path('<slug:slug>/', views.article_detail, name='article_detail'),
    path('category/<str:category>',
         views.article_list, name='articles_by_category'),
]

if settings.DEBUG:
    urlpatterns += static(
         settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

village_tap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
    path('summernote/', include('django_summernote.urls')),
    path("", include("news.urls"), name="news-urls"),
]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.utils.text import slugify


# Create your models here.


CATEGORY_CHOICES = [
    ('news', 'General News'),
    ('traffic', 'Traffic'),
    ('obituaries', 'Obituaries'),
    ('wedding', 'Wedding Announcements'),
    ('history', 'Village History'),
    ('achievements', 'Village Achievements'),
]

DEFAULT_IMAGE_URL = (
    "https://res.cloudinary.com/diz4bvzz9/image/upload/"
    "v1739203594/default_lqlg2e.webp"
)


class Article(models.Model):
    """
    Represents a news article posted on the site.
    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="articles")
    category = models.CharField(
         max_length=50, choices=CATEGORY_CHOICES, default='news')
    blurb = models.TextField(help_text="A short summary of the article.")
    content = models.TextField()
    sources = models.TextField(blank=True, help_text="Optional: list any and"
                               "all resources used in the article.")
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    image = CloudinaryField('image', blank=True, null=True)

    # Status Field
    DRAFT = 1
    PUBLISHED = 2
    ARCHIVED = 3
    STATUS_CHOICES = [
        (DRAFT, 'Draft'),
        (PUBLISHED, 'Published'),
        (ARCHIVED, 'Archived'),
    ]
    status = models.IntegerField(choices=STATUS_CHOICES, default=DRAFT)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f"{self.title} | written by {self.author}"

    def save(self, *args, **kwargs):
        """
        Automatically generates a slug from the title if not provided
        and ensures it's URL-friendly.
        """
        if not self.slug:
            self.slug = slugify(self.title)

        # Apply default image if missing
        if not self.image:
            self.image = DEFAULT_IMAGE_URL

        super().save(*args, **kwargs)

news/forms.py
from .models import Article
from django import forms

# not using crispy because I prefer not to


class ArticleCreationForm(forms.ModelForm):
    class Meta:
        model = Article
        exclude = ['slug', 'created_on', 'status', 'author']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            # using 'rows': to control the height of the text areas
            'blurb': forms.Textarea(attrs={
                'class': 'form-control', 'rows': 4}),
            'content': forms.Textarea(attrs={
                'class': 'form-control', 'rows': 5}),
            'sources': forms.Textarea(attrs={
                'class': 'form-control', 'rows': 3}),
            'status': forms.Textarea(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={
                                    'class': 'form-control-file'}),
        }

    # Get the logged in superuser's name for the author
    def __init__(self, *args, **kwargs):
        user = kwargs.get('user', None)
        super(ArticleCreationForm, self).__init__(*args, **kwargs)

        if user:
            self.fields['author'].initial = user

news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator

from .models import Article
from .models import CATEGORY_CHOICES
from .forms import ArticleCreationForm

# Create your views here.


def article_list(request, category=None):
    """
    Display a list of :model:`news.Article` filtered by category if provided,
    with paginator support.

    **Context**
    ``articles``
        A queryset of :model:`news.Article`,
        filtered by status and optionally category.
    ``category``
        A string representing the category title or
        `None` if no category is specified.
    ``page_obj``
        Paginator object for template pagination controls
    ``is_paginated``
        Boolean for showing pagination controls

    **Template**
    :template:`news/index.html`
    """
    if category:
        # Filter articles by their status (2, Approved) and match the category
        articles = Article.objects.filter(
            status=2,
            category=category).order_by('-created_on')
        # Get the category name to display in the template
        category_title = dict(CATEGORY_CHOICES).get(
             category, 'Unkwown category')
    else:
        articles = Article.objects.filter(status=2).order_by('-created_on')
        category_title = None

    # Paginator - 8 articles per page
    paginator = Paginator(articles, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'news/index.html', {
     'articles': articles,
     'page_obj': page_obj,
     'is_paginated': page_obj.has_other_pages(),
     'category': category_title,
    })


def article_detail(request, slug):
    """
    Display an individual :model:`news.Article`.

    **Context**
    ``article``
        An instance of :model:`news.Article`.

    **Template:**
    :template:`news/article_detail.html`
    """
    queryset = Article.objects.filter(status=2)
    article = get_object_or_404(queryset, slug=slug)

    return render(
        request,
        "news/article_detail.html",
        {"article": article},
    )


def articles_by_category(request, category):
    """
    Display a list of :model:`news.Article` filtered by a specific category.

    **Context**
    ``articles``
        A queryset of :model:`news.Article` filtered by the specified category.

    **Template**
    :template:`news/article_list`
    """
    articles = Article.objects.filter(
         category=category).order_by('-created_on')
    return render(request, 'news/article_list', {
        'articles': articles,  # Pass the filtered articles to the template
    })


def is_superuser(user):
    return user.is_superuser


@login_required
def create_article(request):
    """
    Allow superusers to create a new :model:`news.Article`.

    **Permissions**
    Accessible only to superusers. Unauthorized users are
    redirected to the login page.

    **Context**
    ``form``
        An instance of :form:`news.ArticleCreationForm`.

    **Template**
    :template:`news/create_article.html`
    """
    if not request.user.is_superuser:
        messages.error(request, "Only site admins can create articles.")
        return redirect('home')

    if request.method == 'POST':
        form = ArticleCreationForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            # Auto-generating the slug
            article.slug = article.title.lower().replace(' ', '-')
            # Assign current superuser as the author
            article.author = request.user
            # Set the article status to published
            article.status = Article.PUBLISHED
            article.save()
            messages.success(request, 'Your article has been'
                                      'posted successfully!')
            # Redirects to home after submission
            return redirect('home')
    else:
        form = ArticleCreationForm()

    return render(request, 'news/create_article.html', {'form': form})

news/templates/news/article_detail.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}

<!-- Article Image -->
<div class="masthead">
    <div class="container">
        <div class="row g-0 justify-content-center">
            <!-- Image Section -->
            <div class="col-12 d-flex justify-content-center mb-3">
                {% if article.image %}
                    <img src="{{ article.image.url }}" class="masthead-img img-fluid rounded shadow" alt="{{ article.title }}">
                {% else %}
                    <img src="https://res.cloudinary.com/diz4bvzz9/image/upload/v1739203594/default_lqlg2e.webp" 
                         class="masthead-img img-fluid rounded shadow"
                         alt="{{ article.title }}">
                {% endif %}
            </div>

            <!-- Title, author, date and category -->
            <div class="col-12 text-center mt-3">
                <h1 class="post-title">{{ article.title }}</h1>
                <p class="text-center">{{ article.blurb }}</p>
                <hr>
                <p class="post-subtitle text-muted">{{ article.author }} | {{ article.created_on }}</p>
                <a class="btn article-detail-button" href="{% url 'articles_by_category' article.category %}">
                    {{ article.category }}
                </a>
            </div>
        </div>
    </div>
</div>

<!-- Article -->
<div class="container mt-4 mb-5">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <!-- Main Content -->
            <p class="article-detail-card-text">{{ article.content | safe }}</p>
            <!-- Sources Section -->
            {% if article.sources %}
                <hr>
                <h5 class="mt-4">Sources</h5>
                <p class="text-muted">{{ article.sources }}</p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

news/templates/news/create_article.html
{% extends "base.html" %}

{% block content %}

<div class="container mt-5 mb-5">
    <h1>Create New Article</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

news/templates/news/index.html
{% extends "base.html" %}
{% load static %}
{% load cloudinary_extras %}

{% block header %}
<!-- Header for the Home page -->
<header class="header"
    style="background-image: url('https://res.cloudinary.com/diz4bvzz9/image/upload/v1738429667/header_zlxvqm.jpg');">
    <div class="container position-relative">
        <div class="row justify-content-center align-items-center" style="height: 60vh;">
            <div class="col-12 text-center">
                <div class="site-heading">
                    <h1>The Village Tap</h1>
                    <span class="subheading">News, Views, and Chats – All from Our Village, for Our Village.</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock header %}


{% block content %}

{% if category %}
<h3 class="text-start ms-3 mt-3">{{ category }}</h3>
<hr>
{% endif %}

<div class="container-fluid">
    <div class="row">

        <!-- Articles Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for article in page_obj %}
                    <div class="col-12 col-sm-6 col-lg-3 mb-4">
                        <div class="card article-card h-100 shadow-sm">
                            <a href="{% url 'article_detail' article.slug %}" class="article-link">
                                <img src="{{ article.image.url|cloudinary_small }}" class="card-img-top" alt="{{ article.title }}" loading="lazy">
                            </a>
                            <div class="card-body article-card-body">
                                <a href="{% url 'article_detail' article.slug %}" class="article-link">
                                    <h2 class="card-title">{{ article.title }}</h2>
                                </a>
                                <div class="article-blurb">
                                    <h4 class="card-blurb">{{ article.blurb }}</h4>
                                </div>

                                <hr>
                                <p class="card-text text-muted h6">Published on {{ article.created_on|date:"M j, Y"}} | Author: {{ article.author }}
                                </p>
                                <a class="btn categories-buttons"
                                    href="{% url 'articles_by_category' article.category %}">{{ article.get_category_display }}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- Pagination -->
    {% if is_paginated %}
    <nav aria-label="Page navigation" class="pagination-wrapper">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV</a>
            </li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active">
                        <span class="page-link">{{ num }}</span>
                    </li>
                {% else %}
                    <li class="pag-item">
                        <a href="?page={{ num }}" class="page-link">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

{% endblock %}